#!/usr/bin/env bash
# This script configures an Ubuntu server to have localhost resolve to 127.0.0.2 and facebook.com to 8.8.8.8

echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
