#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

copy C:\Windows\System32\drivers\etc\hosts %userprofile%\hosts.new
echo "127.0.0.2		localhost" > %userprofile%\hosts.new
echo "8.8.8.8		facebook.com" >> %userprofile%\hosts.new
copy /y %userprofile%\hosts.new C:\Windows\System32\drivers\etc\hosts
